apiVersion: v1
kind: Service
metadata:
  name: {{ include "mobsf.fullname" . }}
  labels:
    {{- include "mobsf.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
  selector:
    {{- include "mobsf.selectorLabels" . | nindent 4 }}
